services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    networks:
      - default
    restart: unless-stopped
    environment:
    - TZ=${TZ:-Etc/UTC}
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        protocol: tcp
        mode: host
    volumes:
    - ./mosquitto/mosquitto-config:/mosquitto/config
    - /home/pi/iot_data/mosquitto/log:/mosquitto/log/
    - /home/pi/iot_data/mosquitto/data:/mosquitto/data/
  soil-sensor:
    container_name: soil-sensor
    image: soil-sensor:latest
    hostname: ${HOSTNAME}
    networks:
      - default
    devices:  
      - "/dev/i2c-1:/dev/i2c-1"  
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./soil_sensor.py:/usr/app/src/soil_sensor.py
    command: sh -c "sleep 10s ; python3 ./soil_sensor.py"
    depends_on:
      - mosquitto