services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    networks:
      - default
    restart: unless-stopped
    user: "1883:1883"
    healthcheck:
      test: ping soil-sensor -c 1 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - TZ=${TZ:-Etc/UTC}
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        protocol: tcp
        mode: host
    volumes:
    - ./config:/mosquitto/config
    #command: |
    #  sh -c "
    #    cat > /mosquitto/config/mosquitto.conf << EOF
    #    listener 1883
    #    allow_anonymous true
    #    persistence false
    #    log_dest stdout
    #    EOF
    #    /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
    #  "
    
  soil-sensor:
    container_name: soil-sensor
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - soil-sensor:latest
    image: soil-sensor:latest
    devices:  
      - "/dev/i2c-1:/dev/i2c-1"  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "soil_sensor.py", "check_health"]
      start_period: 120s
      interval: 10s
      retries: 3
      timeout: 30s
    environment:
      - TZ=${TZ:-Etc/UTC}
      - SENSOR_NAME=${SENSOR_NAME:-unknown_sensorname}
      - ENVIRONMENT=${ENVIRONMENT}
      - PYTHONPATH=/app/src:/usr/lib/python3/dist-packages
#    volumes:
#      - ./soil_sensor.py:/usr/app/src/soil_sensor.py
    command: sh -c "sleep 10s ; python3 ./soil_sensor.py"
    depends_on:
      - mosquitto

  test-runner:
    build:
      context: .
      dockerfile: tests/Dockerfile
    working_dir: /app/tests
    devices:  
      - "/dev/i2c-1:/dev/i2c-1"  
    environment:
      - PYTHONPATH=/app/src:/app/tests:/usr/lib/python3/dist-packages
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    profiles:
      - test
