services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ping soil-sensor -c 1 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - TZ=${TZ:-Etc/UTC}
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        protocol: tcp
        mode: host
    volumes:
    - ./mosquitto-config:/mosquitto/config
    
  soil-sensor:
    container_name: soil-sensor
    build: ./
    image: soil-sensor:latest
    networks:
      - default
    devices:  
      - "/dev/i2c-1:/dev/i2c-1"  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "soil_sensor.py", "check_health"]
      start_period: 120s
      interval: 10s
      retries: 3
      timeout: 30s
    environment:
      - TZ=${TZ:-Etc/UTC}
      - SENSOR_NAME=${SENSOR_NAME:-unknown_sensorname}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./soil_sensor.py:/usr/app/src/soil_sensor.py
    command: sh -c "sleep 10s ; python3 ./soil_sensor.py"
    depends_on:
      - mosquitto